version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 5
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 5
  ignore:
  - # Needs to be updated along with NodeJS version.
    dependency-name: "@types/node"
    update-types: [version-update:semver-major]
