version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 5
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 5
